import Head from "next/head";

export default function SinglePost() {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="flex w-1/2 flex-col"> Single Post Page</div>
      </main>
    </>
  );
}
